# app/config/routing.yml

bajor_web_service:
    resource: "@BajorWebServiceBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    

#bajor_web_api:
#    resource: "@BajorWebServiceBundle/Resources/config/routing.yml"
#    prefix:   /api
