bajor_web_service_homepage:
    path:     /hello/{name}
    defaults: { _controller: BajorWebServiceBundle:Default:index }
    
bajor_web_service_hello:
    path:     /soap
    defaults: { _controller: BajorWebServiceBundle:HelloService:index }
    
bajor_api_soap_check:
    path: /api/soap/check
    defaults: { _controller: BajorWebServiceBundle:Soap:check }
