bajor_form:
    path:     /
    defaults: { _controller: BajorWebServiceBundle:Default:index }

bajor_form_resolved:
    path:     /resolved
    defaults: { _controller: BajorWebServiceBundle:Default:resolved }
    
    

    
bajor_api_equation_quadratic:
    path: /api/equation/quadratic
    defaults: { _controller: BajorWebServiceBundle:Equation:quadratic }
